### ISSUE TITLE
Please don't use my profile picture

### ISSUE THREAD

**Issue by 00p513-dev** [wiz64/stacy#5]

**Comment by wiz64** [comment]
copyright it 🥲 
idk how you got the same dp lol, in newer version i've used images generated from Craiyon

**Comment by 00p513-dev** [comment]
Craiyon did not exist at that time, and it is still in the README. Please remove it

**Comment by wiz64** [comment]
> Craiyon did not exist at that time, and it is still in the README. Please remove it

well I can use that photo, its on public domain :P neither its a trademark nor a copyright.  dall-e-mini did exist at that time.
Btw, did you yourself create this profile picture ?

**Comment by wiz64** [comment]
I'll update things in newer versions as I am working GPT-3 plugin for stacy, but I'll still call this her baby face.

**Comment by 00p513-dev** [comment]
> > Craiyon did not exist at that time, and it is still in the README. Please remove it
> 
> well I can use that photo, its on public domain :P neither its a trademark nor a copyright. dall-e-mini did exist at that time. Btw, did you yourself create this profile picture ?

it is not public domain, and yes I did create it. please take it down

**Comment by 00p513-dev** [comment]
you have previously reached out to me on telegram and I did not give you permission. I explicitly said no.
